---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  require_chef_omnibus: 12
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[kingsly_certbot::ipsec]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      kingsly_certbot:
        config:
          top_level_domain: 'example.com'
          sub_domain: 'sub'
          kingsly_server_host: 'kingsly-server.example.com'
          kingsly_server_user: '***'
          kingsly_server_password: '***'
          server_type: 'ipsec'
          ipsec_root: '/'
