name 'kingsly-certbot'
maintainer 'GO-JEK Developers'
maintainer_email 'foss+farm@go-jek.com'
license 'All Rights Reserved'
description 'Installs/Configures kingsly_certbot'
long_description 'Installs/Configures kingsly_certbot'
version '0.2.2'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/gojekfarm/kingsly-certbot-cookbook/issues'
source_url 'https://github.com/gojekfarm/kingsly-certbot-cookbook'
